payara/MicroProfile-TCK-Runners

MicroProfile-JWT-Auth/tck-arquillian-extension/src/main/java/fish/payara/microprofile/jwtauth/tck/TokenParser.java
I'm not able to get this compiling against the linked PR, and this will also break the TCK runner suite for all old versions of Payara. I would suggest instead making use of the new maven regex profile activator to work around this.
=> Revert "QA-198 Refactor JsonWebToken API in MP TCK Runner JWT Auth"

MicroProfile-Health/tck-runner/pom.xml
Caused by unwanted dependency inheritance in tck-arquillian-extension pom
Tested against micro-managed, server-managed and server-remote
=> [TEST-293] - Unable to run MicroProfile TCK Health on payara-micro-managed

.gitignore, MicroProfile-Rest-Client/tck-runner/pom.xml
Upgrades to service version of the TCK, which passes with our 2.29 Jersey release.
Depends on payara/Payara_PatchedProjects#242
=> Use REST Client TCK version 1.2.1

MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite2.0.xml
Raw part of running MP FT 2.0 TCK. 
For now this PR just adds a suite file that has the configuration I used when testing. It includes all tests `tck.*` but then excludes those where a specific exception is expected at deployment time. These fail in the TCK since we wrap the exception in a way that will not be discovered by Arquillian. To make sure we do a similar test I added unit tests to the implementation that check the setups from the excluded TCK tests do cause a `FaultToleranceDefinitionException`. Then there are 2 excluded methods for bulkhead that are excluded since they make expectations about the implementation that aren't necessarily true. I made a PR to FT https://github.com/eclipse/microprofile-fault-tolerance/pull/426 to relax the asserts. See that PR for more details.
My …
=> PAYARA-3468 Added suite suitable to run MP FT 2.0 TCK

MicroProfile-Rest-Client/tck-runner/pom.xml
ee8-client still depends on Jersey 2.27, and its internals differ to those of 2.29, therefore it had to be excluded.
=> TEST-337: Update rest client artifact and exlude conflicting dependencies

MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite2.0-stable.xml
This PR adds a suite for stable tests. This currently excludes the `BulkheadMetricTest` which can fail in various methods because of counts differing by 1. There seems some kind of race condition allowing an off-by-one count. 
The new suite file is used as default for `payara.version` activated profiles using normally when running the tests.
=> TEST-340 Added "stable" Suite for FT 2.0

MicroProfile-Fault-Tolerance/tck-runner/pom.xml
Seems micro was forgotten from a previous change relating to Microprofile 2.0 and a stability fix. This change makes use of the new property for suite file
=> TEST-350 Corrected which suite micro should be using

MicroProfile-Fault-Tolerance/tck-runner/pom.xml
For compatibility with MP Metrics 2.0
for https://github.com/payara/Payara/pull/4108
=> PAYARA-4013 Upgrade MP Fault tolerance version to 2.0.1

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml, MicroProfile-JWT-Auth/tck-arquillian-extension/src/main/java/fish/payara/microprofile/jwtauth/tck/MockTokenParser.java
Reverted state of MockTokenParser to match requirements of 5.192 and below and repaired regex statement in pom.xml to exclude the build in class when testing 5.193-SNAPSHOT and later - Resolves JWT-Auth TCK failure against Payara 4 versions
=> [TEST-369] - Resolved MP JWT-Auth failure

MicroProfile-Rest-Client/tck-runner/pom.xml
Created a separate property for the MP API version so as to not pull in an old version when testing against Payara 4 - Tests now pass on 4 and 5
=> [TEST-361] - MP Rest-Client TCK fails on Payara 4

pom.xml
These classes were removed in JDK 11 and have been made a part of EE.
=> Add dependency for classes removed from JDK

MicroProfile-Rest-Client/tck-runner/pom.xml
Payara 5.192 included a Rest Client version update.
These changes should allow us to run the TCK against 5.191 and 5.192+ without constantly having to faff about with the dependencies & versions.
=> Fix rest client maintenance branches

MicroProfile-JWT-Auth/tck-runner/pom.xml
There was a missing dependency exclusion in the tck-runner pom that is causing the test suite to error out when running against 5.194+
Tested locally without change: Fails
Tested locally with change: Passes
=> [PAYARA-4148] - Added missing dependency exclusion

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml
Regular Expression was recognising 5.194 as valid version thus breaking that test version - this PR resolves that issue
=> [PAYARA-4148] - Updated Regular Expression

MicroProfile-Metrics/tck-runner/pom.xml
Regular expressions in metrics weren't correctly matching versions in test suite - this PR updates them to match correctly
=> Fixed regular expressions to match correctly

MicroProfile-Rest-Client/tck-runner/pom.xml
Payara 4 fails Rest Client TCK due to incorrect API version number
=> [TEST-120] - Fix Class Not Found Error against Payara 4

MicroProfile-Metrics/tck-runner/pom.xml
Project type was causing arquillian profile to not get registered during the build meaning Metrics Tests could not run - this PR resolves that
=> Resolved Build Issues

.mvn/extensions.xml
Caused by https://github.com/payara/MicroProfile-TCK-Runners/pull/64.
Version 0.5 of the extension doesn't exist :wink:
Tut tut tut
=> Fix Regex Profile Activator Extension Version

pom.xml
See commit message for details.
Ran the health TCK against 5.194.1 on remote profile (which fails otherwise).
I've added the optional flag to make none of the connectors include themselves transiently.
=> CUSTCOM-116 Leaking Managed Connector Dependency

MicroProfile-OpenTracing/tck-runner/pom.xml, pom.xml
Fixes OpenTracing TCK runner using updated Arquillian container.
Requires release of Arquillian Container 2.1 to apply fix for server-managed.
=> QACI-46 Use updated resteasy-client

MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/bulkhead-metrics.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite2.1-debug.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite2.1-stable.xml
In combination with https://github.com/payara/Payara/pull/4568
FYI: TCK runner will now print info on what the 3 main properties were evaluated to:
```bash
[echo] FT version     2.1
[echo] FT TCK version 2.1
[echo] FT suite       tck-suite2.1-stable.xml
```
Without it it was too unclear what version actually would run for a certain combination of arguments.
In my local testing TCK now passes stable with just a single test disabled that sometimes fails with
> Work is not being done simultaneously enough
which we cannot do something about - the test need to relax their expectations here.
The rest of the tests that are still ignored below the comment
> exception is thrown but wrapped
are those where the container wraps the expected exception so a test cannot verify it correctly - this is …
=> APPSERV-57 Adds 2.1 TCK as new default and new profile

MicroProfile-Config/tck-runner/pom.xml
Profile activation (not actual TCK) tested against:
```
-Dpayara.version=4.1.2.191
-Dpayara.version=4.1.2.191.13
-Dpayara.version=5.194
-Dpayara.version=5.194.2
-Dpayara.version=5.201
-Dpayara.version=5.201.1
-Dpayara.version=5.202
-Dpayara.version=5.202-SNAPSHOT
```
=> Add MicroProfile Config Version Profiles

MicroProfile-Metrics/tck-runner/pom.xml
In connection with PR https://github.com/payara/Payara/pull/4582.
**That PR should be merged first.**
=> APPSERV-59 Adds MicroProfile 2.3 profile

MicroProfile-Config/tck-runner/pom.xml
In connection with https://github.com/payara/Payara/pull/4614
The `MP_CONFIG_CACHE_DURATION` variable is used to disable the cache for TCK run. This will only have any effect on versions that support caching but it does not hurt to be set for any version.
=> APPSERV-141 Adds MP_CONFIG_CACHE_DURATION

MicroProfile-Metrics/tck-runner/pom.xml
We were testing against a version of metrics tck that payara4 doesn't support
=> [QACI-430] - Downgraded TCK Version

MicroProfile-Fault-Tolerance/tck-runner/pom.xml
FISH-659 should revert this, but these need disabling in order for the
Metrics upgrade to proceed independent of FT.
Signed-off-by: Matthew Gill <matthew.gill@live.co.uk>
=> FISH-662 Disable Fault Tolerance TCK

MicroProfile-Metrics/tck-runner/pom.xml
Reverts payara/MicroProfile-TCK-Runners#127
Looks good to merge Metrics again as FT has been disabled, so the TCK can be upgraded again.
=> Re-integrate FISH-662 MicroProfile Metrics 3.0 (MP 4.0)

MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite3.0-stable.xml
Removes all excluded classes and timeout multiplier, as new version (to be posted) passes all of them
=> FISH-659: Full FT 3.0 run

MicroProfile-OpenAPI/tck-runner/pom.xml, MicroProfile-OpenAPI/tck-runner/src/test/resources/tck-suite.xml
Needed to upgrade Arquillian and JCommander for the TCK to run correctly. Maybe there's a better way to do this, I'm not sure
One TCK test has been disabled, with a linked issue to explain why
=> FISH-663 MicroProfile OpenAPI 2.0 TCK Upgrade (MP 4.0)

MicroProfile-Rest-Client/tck-runner/pom.xml
This reverts commit 263a78c9440bccb4d90f8bd42013c26e10cb5f9c, reversing
changes made to 38c9d0ceaddc9ccffde01dadfd5762a95e4cdf66.
Original PR was made to the incorrect branch, see https://github.com/payara/MicroProfile-TCK-Runners/pull/136 for replacement
=> [FISH-665] - Revert "Merge pull request #134 from jGauravGupta/FISH-665"

MicroProfile-Config/tck-runner/src/test/resources/tck-suite.xml
This class was disabled in error, and revealed a hole in functionality
=> FISH-658 Enable @ConfigProperties tests

MicroProfile-Config/tck-runner/pom.xml, MicroProfile-Config/tck-runner/src/test/resources/tck-suite.xml
Re enable tests failing because of lack of system properties, as managed profile now configured them before running the TCKs.
=> FISH-1060 Configure MP Config System Properties

MicroProfile-Config/tck-runner/pom.xml, MicroProfile-Config/tck-runner/src/test/resources/arquillian.xml
The systemPropertyVariables block in the payara-micro config doesn't pass properties to the micro instance as expected. I've changed the configuration to utilise the cmdOptions arquillian config to pass it to the micro instance on the command line.
Should resolve issue seen at http://192.168.1.120:8080/job/TestMPTCKs/2589/testReport/junit/org.eclipse.microprofile.config.tck.configsources/DefaultConfigSourceOrdinalTest/Test_MP_Config_TCK___testOrdinalForEnv/
=> QACI-625 MP Config Micro System Properties Fix

MicroProfile-OpenTracing/pom.xml, MicroProfile-OpenTracing/src/test/resources/tck-suite.xml, pom.xml
Title.
The TCK expects BigDecimal as that's what JSON-B expects.
Jackson returns Integers and is therefore incorrect.
Linked PRs:
* https://github.com/payara/patched-src-microprofile-opentracing/pull/2
* https://github.com/payara/ecosystem-arquillian-connectors/pull/145
* https://github.com/payara/ecosystem-arquillian-connectors/pull/146
=> FISH-5683 Use BigDecimal inline with the TCK

MicroProfile-Config/pom.xml, MicroProfile-Metrics/pom.xml, MicroProfile-Rest-Client/apache-httpclient-connector/pom.xml, MicroProfile-Rest-Client/tck-runners/pom.xml
This appears to be something within Arquillian or the TCK itself, so just adding --opens for now.
Also updates the bundle plugin to a version which likes JDK 17.
=> FISH-5870 InaccessibleObjectException in MicroProfile Config & Rest Client on JDK 17

MicroProfile-JWT-Auth/pom.xml
They bumped the Jose version to fix the issue.
Tested against JDK 8, 11, and 17.
=> FISH-5871 InvalidAlgorithmException in MicroProfile JWT on JDK 17

MicroProfile-Health/pom.xml, MicroProfile-Health/tck-runner/pom.xml, MicroProfile-Health/tck-runner/src/test/resources/tck-suite.xml
Brings down a required dependency for JDK 17.
This dependency should probably have been present for all versions, but Jackson managed to squeeze by.
Also updates some associated text and dependencies to align with the version of MP Health we actually use.
=> FISH-5872 Fix Health TCK for JDK 17

MicroProfile-Config/pom.xml, MicroProfile-Config/src/main/java/fish/payara/microprofile/config/tck/ArquillianArchiveProcessor.java, MicroProfile-Config/src/main/resources/beans.xml, MicroProfile-Fault-Tolerance/pom.xml, MicroProfile-Fault-Tolerance/src/main/java/fish/payara/microprofile/ft/tck/ApplicationArchiveProcessorImpl.java, MicroProfile-Fault-Tolerance/src/main/java/fish/payara/microprofile/ft/tck/ArquillianExtension.java, MicroProfile-Fault-Tolerance/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, MicroProfile-Fault-Tolerance/src/main/resources/beans.xml, MicroProfile-Metrics/pom.xml, MicroProfile-Metrics/src/main/java/fish/payara/microprofile/metrics/tck/ApplicationArchiveProcessorImpl.java, MicroProfile-Metrics/src/main/java/fish/payara/microprofile/metrics/tck/ArquillianExtension.java, MicroProfile-Metrics/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, MicroProfile-Metrics/src/main/resources/beans.xml, MicroProfile-OpenTracing/pom.xml, MicroProfile-OpenTracing/src/test/java/fish/payara/arquillian/extension/ArquillianExtension.java, MicroProfile-OpenTracing/src/test/java/fish/payara/writer/ApplicationArchiveProcessorImpl.java, MicroProfile-OpenTracing/src/test/java/fish/payara/writer/AutoDiscoverableImpl.java, MicroProfile-OpenTracing/src/test/java/fish/payara/writer/MessageBodyWriterProvider.java
This PR is a rework of the previous PR https://github.com/payara/MicroProfile-TCK-Runners/pull/186 since it is using patched version of TCKs that cannot be certified.
Removed patched version of TCKs, redefine beans definition by reprocessing it with beans mode `all`
=> FISH-6409 Fix MP TCK issues on Payara6-tck
