MicroProfile-OpenAPI/README.md, MicroProfile-OpenAPI/tck-runner/.classpath, MicroProfile-OpenAPI/tck-runner/.project, MicroProfile-OpenAPI/tck-runner/.settings/org.eclipse.core.resources.prefs, MicroProfile-OpenAPI/tck-runner/.settings/org.eclipse.jdt.core.prefs, MicroProfile-OpenAPI/tck-runner/.settings/org.eclipse.m2e.core.prefs, MicroProfile-OpenAPI/tck-runner/pom.xml, MicroProfile-OpenAPI/tck-runner/src/test/resources/tck-suite.xml
Relies on PR: https://github.com/payara/Payara_PatchedProjects/pull/152
=> Added OpenAPI TCK

MicroProfile-Config/tck-runner/pom.xml, MicroProfile-Config/tck-runner/src/test/resources/no-ext-libs-tck-suite.xml
Signed-off-by: Steve Millidge <steve.millidge@payara.fish>
=> PAYARA-2851 Added environment variables for tests

MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/no-ext-libs-tck-suite.xml
https://github.com/payara/Payara_PatchedProjects/pull/184
=> PAYARA-2721 Update TCK runner for Fault Tolerance 1.1.1

MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/no-ext-libs-tck-suite.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite.xml
https://github.com/payara/Payara/pull/3126
=> PAYARA-3075 Re-enable test

MicroProfile-JWT-Auth/tck-arquillian-extension/src/main/java/fish/payara/microprofile/jwtauth/tck/TokenParser.java
Depends on https://github.com/payara/Payara/pull/3799
=> QA-198 Refactor JsonWebToken API in MP TCK Runner JWT Auth

.mvn/extensions.xml, MicroProfile-OpenAPI/tck-runner/pom.xml
Needed update to 1.1 version of the TCK.
=> PAYARA-3466 Update to Open API TCK to 1.1.2

MicroProfile-Metrics/tck-runner/pom.xml
Relies on https://github.com/payara/Payara/pull/4076
=> PAYARA-3830 Updated MP Metrics version to 2.0.0

MicroProfile-OpenTracing/tck-runner/pom.xml
Depends on https://github.com/payara/Payara_PatchedProjects/pull/274
=> PAYARA-4055: Used patched MP OpenTracing TCK

MicroProfile-JWT-Auth/pom.xml, MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml
This probably needs refactoring out at some point - reflected in comment.
=> Fix Dependency GAV

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml, MicroProfile-JWT-Auth/tck-runner/pom.xml
Added a dependency for the JWT Package in Payara Server to a Payara 5.192- Profile (Activated on all versions below Payara 5.192 inclusive)
=> [PAYARA-4248] - Fixed failure against Payara 4

MicroProfile-Rest-Client/tck-runner/pom.xml
Fixes missing property within the payara4 profile. Without this the maven build using this profile fails
=> PAYARA-4264 fixed missing property

MicroProfile-Metrics/tck-runner/pom.xml
Depends on:  
https://github.com/payara/Payara_PatchedProjects/pull/284
https://github.com/payara/Payara/pull/4328
=> PAYARA-4166 MicroProfile Metrics v2.2.payara-p1 support

MicroProfile-Metrics/tck-runner/pom.xml
Found the issue during testing of https://github.com/payara/Payara/pull/4195
=> PAYARA-4083 Include test class pattern globally

.mvn/extensions.xml
This reverts commit 31f18fb7fb0c0ed551fa52d251502368ebeebe26.
regex profile activator version 0.5 has been released
=> Revert "Fix Regex Profile Activator Extension Version"

MicroProfile-Rest-Client/tck-runner/pom.xml
Also excludes Jersey Client gubbins and adds smallrye dependency
=> QACI-31 QACI-32 Move client-ee8 dependency into 5 profile 

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml
Updates to versioning in maintenance branches required updated version regex in the pom
=> [QACI-43] - Mock Token Parser Missing

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml
Incorrect profiles were activating
Tested against all release versions of Payara server
=> [QACI-43] - Fixed Profile Activations

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml
=> [QACI-43] - Correct Version Activator Syntax

MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite2.0-stable.xml
Fixes previous PR. Method was in wrong class
=> QACI-112 Ignore Disable testBulkheadPassiveRetryMethodSynchronous55

MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite2.0-stable.xml
=> QACI 113 Ignore BulkheadSynchRetryTest.testIgnoreWaitingTaskQueueBulkhead

MicroProfile-Health/pom.xml, MicroProfile-Health/tck-runner/pom.xml
Main PR: https://github.com/payara/Payara/pull/4595
=> APPSERV-60 Use MP Health 2.2

MicroProfile-Config/tck-runner/pom.xml
=> Fix relative path

MicroProfile-Rest-Client/tck-runner/pom.xml
Adds a new profile for 5.202 plus.
Relies on:
* https://github.com/payara/patched-src-microprofile-rest-client/pull/3
* https://github.com/payara/patched-src-jersey/pull/59
* https://github.com/payara/Payara/pull/4624
* https://github.com/payara/Payara_PatchedProjects/pull/298
=> APPSERV-61 Rest Client 1.4

MicroProfile-Config/tck-runner/pom.xml, MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Health/tck-runner/pom.xml, MicroProfile-Metrics/tck-runner/pom.xml, MicroProfile-OpenAPI/tck-runner/pom.xml, MicroProfile-Rest-Client/tck-runner/pom.xml
Update for new versioning system within the test suites - Legacy versions should be tested against the "old-payara-versioning" branch
=> [QACI-231] - Created Enterprise And Community Profiles

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml
Some profiles missed during the great purge of the old versioning system.
=> QACI-251 Reliant On Build Artifact That is Not Distributed

MicroProfile-Rest-Client/tck-runner/pom.xml
Patched artifact: payara/Payara_PatchedProjects#314
Code changes: payara/patched-src-microprofile-rest-client/pull/4
=> QACI-258 MPTCKs Micro managed address already in use

pom.xml
The arquillian container has been updated. I have updated the test suites to match.
It was noted that there are overriding properties which caused problems. I have removed the overriding properties, and the payara4 profile as the payara4 profile is run from a different branch of this test suite
=> QACI-259 New Arquillian version

MicroProfile-JWT-Auth/tck-arquillian-extension/pom.xml
Duplication of https://github.com/payara/MicroProfile-TCK-Runners/pull/111/files onto old-payara-versioning branch
=> QACI-251 update profile activation

MicroProfile-Health/pom.xml, MicroProfile-Health/tck-runner/pom.xml
I've created a new MP 4.0 branch to push to. This will be followed with a Payara branch to test against
=> FISH-660 Health 3.0-RC5 TCK Upgrade

MicroProfile-Config/tck-runner/pom.xml, MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Health/tck-runner/pom.xml, MicroProfile-Metrics/tck-runner/pom.xml, MicroProfile-OpenAPI/tck-runner/pom.xml, MicroProfile-Rest-Client/tck-runner/pom.xml
No idea why this is here, it messes with the TCK runners by opaquely changing TCK versions. This is what Git tags and branches are for right?
=> FISH-660 Remove Community Profile

MicroProfile-JWT-Auth/pom.xml, MicroProfile-JWT-Auth/tck-runner/src/test/resources/base-tck-suite.xml
A few tests had to be removed. Who checks which tests we're actually running? We seem to be skipping a tonne, but I'm not sure if that's always been the case
=> FISH-661 JWT Auth 1.2-RC2 TCK Upgrade

MicroProfile-Metrics/tck-runner/pom.xml
TCK update in connection with https://github.com/payara/Payara/pull/5002
=> FISH-662 MicroProfile Metrics 3.0 (MP 4.0)

MicroProfile-Metrics/tck-runner/pom.xml
Reverts payara/MicroProfile-TCK-Runners#126
As discussed in teams
=> Revert "FISH-662 MicroProfile Metrics 3.0 (MP 4.0)"

MicroProfile-OpenTracing/tck-runner/pom.xml
https://github.com/payara/patched-src-microprofile-opentracing/pull/1
https://github.com/payara/Payara_PatchedProjects/pull/347
=> FISH-664 Upgrade to MP OpenTracing TCK 2.0-RC2.payara-p1

MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Fault-Tolerance/tck-runner/src/test/resources/tck-suite3.0-stable.xml
Just to share the TCK runner setup I used so far when testing https://github.com/payara/Payara/pull/5023
Don't know why I got changes in other runners but obviously only the ones for the FT runner are relevant when testing FT.
=> FISH-659 Micro Profile Fault tolerance 3.0

MicroProfile-Rest-Client/tck-runner/pom.xml
A replacement for https://github.com/payara/MicroProfile-TCK-Runners/pull/134 which was merged into the wrong branch of upstream
=> [FISH-665] - Correct target branch

MicroProfile-Fault-Tolerance/tck-runner/pom.xml, MicroProfile-Health/pom.xml, MicroProfile-Health/tck-runner/pom.xml, MicroProfile-JWT-Auth/pom.xml, MicroProfile-Metrics/tck-runner/pom.xml, MicroProfile-OpenAPI/tck-runner/pom.xml, MicroProfile-OpenTracing/tck-runner/pom.xml
Waiting for OpenTracing patched version to be published
=> FISH-882 Finalise MP 4.0 TCK versions

MicroProfile-Config/tck-runner/pom.xml, MicroProfile-Config/tck-runner/src/test/resources/tck-suite.xml
Test fails due to not being pased through from maven
=> Exclude test depending on system property

MicroProfile-Config/tck-runner/src/test/resources/tck-suite.xml
Missed in https://github.com/payara/MicroProfile-TCK-Runners/pull/139/files
=> Exclude test depending on environment variable

MicroProfile-Config/src/test/resources/tck-suite.xml, pom.xml
Requires a release of the Arquillian Connectors, pending PR: https://github.com/payara/ecosystem-arquillian-connectors/pull/133
=> FISH-1060 Re-enable MP Config tests

MicroProfile-JWT-Auth/pom.xml
=> FISH-1504 JWT AUTH 1.2.1

MicroProfile-Health/tck-runner/pom.xml
=> FISH-666 FISH-667 FISH-1372 MicroProfile 4.1

MicroProfile-JWT-Auth/tck-runner/pom.xml, MicroProfile-JWT-Auth/tck-runner/src/test/resources/base-tck-suite.xml, MicroProfile-JWT-Auth/tck-runner/src/test/resources/full-tck-suite.xml
Title.
Main Repo PR: https://github.com/payara/Payara/pull/5372
=> FISH-1520 Add Missing JWT-Auth Tests

MicroProfile-Rest-Client/apache-httpclient-connector/pom.xml
See if this fixes sporadic failure in compilation
=> Update bundle plugin

MicroProfile-OpenTracing/pom.xml
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>
=> Explanative comment

src/test/resources/arquillian.xml
Reverts payara/MicroProfile-TCK-Runners#177
=> Revert "Set allowConnectingToRunningServer property to true"

MicroProfile-Config/pom.xml, MicroProfile-Fault-Tolerance/pom.xml, MicroProfile-Metrics/pom.xml, MicroProfile-OpenTracing/pom.xml, MicroProfile-OpenTracing/src/test/java/fish/payara/arquillian/extension/ArquillianExtension.java, MicroProfile-OpenTracing/src/test/java/fish/payara/writer/ApplicationArchiveProcessorImpl.java, MicroProfile-OpenTracing/src/test/java/fish/payara/writer/AutoDiscoverableImpl.java, MicroProfile-OpenTracing/src/test/java/fish/payara/writer/MessageBodyWriterProvider.java, MicroProfile-OpenTracing/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
Fixed below TCKs:
+ Fault tolerance
+ Metrics
+ Config
+ Opentracing 
+ https://github.com/payara/patched-src-microprofile-config/pull/1
+ https://github.com/payara/patched-src-microprofile-metrics/pull/4
+ https://github.com/payara/patched-src-microprofile-fault-tolerance/pull/8
WSL 2.0 - Ubuntu 20.04.4 LTS, OpenJDK11, Maven 3.8.6
```
[INFO] Reactor Summary for MicroProfile TCK Suite Parent 1.1-SNAPSHOT:
[INFO]
[INFO] MicroProfile TCK Suite Parent ...................... SUCCESS [ 17.955 s]
[INFO] MicroProfile Fault Tolerance TCK Runner ............ SUCCESS [07:03 min]
[INFO] MicroProfile JWT-Auth TCK Runner Parent ............ SUCCESS [  0.066 s]
[INFO] MicroProfile JWT Auth TCK Arquillian Extension ..... SUCCESS [  0.809 s]
[INFO] MicroProfile JWT-Auth TCK Runner ................... …
```
=> FISH-6409 Fix MP TCK issues on Payara6-tck

pom.xml
Missing port of https://github.com/payara/MicroProfile-TCK-Runners/pull/176
=> Add web profile support for payara-server-managed (MP 5.0)

pom.xml
Missing port of https://github.com/payara/MicroProfile-TCK-Runners/pull/176
=> Add web profile support for payara-server-managed (MP 3.3)

pom.xml
Missing port of https://github.com/payara/MicroProfile-TCK-Runners/pull/176
=> Add web profile support for payara-server-managed (MP 4.0)
